language: node_js
sudo: required
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate
  - rm -rf .deploy_git || true

after_script:
  - git config user.name "wusphinx"
  - git config user.email "wu.sphinx@gmail.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
